In [ ]:
import numpy as np
import pandas as pd

In [ ]:

## creating a sample data
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [ ]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [ ]:
## intialize w,b,layer dim
def intialize_parameters(layer_dims):

  np.random.seed(3)
  parameters ={}
  L = len(layer_dims)
  for l in range(1,L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
  return parameters


In [ ]:
intialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
## used to calculate output for particular neurons
def linear_forward(A_prev,W,b):
  Z = np.dot(W.T,A_prev)+b
  return Z

In [ ]:
## forward prop
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2 # num of layers in the neural network
  for l in range(1,L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    print('A'+str(l-1)+':',A_prev)
    print('W'+str(l)+':',W1)
    print('b'+str(l)+':',b1)
    print('--'*20)

    A = linear_forward(A_prev,W1,b1)
    print('A'+str(l)+':',A)
    print('**'*20)

  return A,A_prev


In [ ]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['lpa']].values[0][0]
# parameter intialization
parameters = intialize_parameters([2,2,1])

y_hat,A1= L_layer_forward(X,parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************


In [ ]:
y_hat = y_hat[0][0]

##(y-0.32)**2 ### loss for the first student

In [ ]:
A1

array([[1.6],
       [1.6]])

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 *(y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 *(y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 *(y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 *(y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 *(y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 *(y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 *(y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 *(y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 *(y-y_hat)*parameters['W2'][1][0])


In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

In [ ]:
parameters


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [ ]:
#### process for 1 student is completed and weights and bias are updated one time


In [ ]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['lpa']].values[1][0]
## now for second student
y_hat,A1= L_layer_forward(X,parameters)

A0: [[7]
 [9]]
W1: [[0.16554791 0.16554791]
 [0.16554791 0.16554791]]
b1: [[0.00819349]
 [0.00819349]]
----------------------------------------
A1: [[2.6569601]
 [2.6569601]]
****************************************
A1: [[2.6569601]
 [2.6569601]]
W2: [[0.19715237]
 [0.19715237]]
b2: [[0.20712303]]
----------------------------------------
A2: [[1.25477497]]
****************************************


In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_11778/2166773343.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 *(y-y_hat)*A1[0][0])
/tmp/ipykernel_11778/2166773343.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 *(y-y_hat)*A1[1][0])
/tmp/ipykernel_11778/2166773343.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.

In [ ]:
parameters


{'W1': array([[0.17692875, 0.18018042],
        [0.17692875, 0.18018042]]),
 'b1': array([[0.00981932],
        [0.00981932]]),
 'W2': array([[0.21705419],
        [0.21705419]]),
 'b2': array([[0.22454464]])}

In [ ]:
X = df[['cgpa','profile_score']].values[2].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['lpa']].values[2][0]
## now for 3rd student
y_hat,A1= L_layer_forward(X,parameters)

A0: [[ 6]
 [10]]
W1: [[0.17692875 0.18018042]
 [0.17692875 0.18018042]]
b1: [[0.00981932]
 [0.00981932]]
----------------------------------------
A1: [[2.84067929]
 [2.89270597]]
****************************************
A1: [[2.84067929]
 [2.89270597]]
W2: [[0.21705419]
 [0.21705419]]
b2: [[0.22454464]]
----------------------------------------
A2: [[1.46899995]]
****************************************


In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_11778/2166773343.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 *(y-y_hat)*A1[0][0])
/tmp/ipykernel_11778/2166773343.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 *(y-y_hat)*A1[1][0])
/tmp/ipykernel_11778/2166773343.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.

In [ ]:
parameters

{'W1': array([[0.19013008, 0.20218263],
        [0.19015571, 0.20222535]]),
 'b1': array([[0.01201954],
        [0.01202382]]),
 'W2': array([[0.24279643],
        [0.24326789]]),
 'b2': array([[0.25232989]])}

In [ ]:
X = df[['cgpa','profile_score']].values[3].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['lpa']].values[3][0]
##4th student
y_hat,A1= L_layer_forward(X,parameters)

A0: [[ 5]
 [12]]
W1: [[0.19013008 0.20218263]
 [0.19015571 0.20222535]]
b1: [[0.01201954]
 [0.01202382]]
----------------------------------------
A1: [[3.24453845]
 [3.44964118]]
****************************************
A1: [[3.24453845]
 [3.44964118]]
W2: [[0.24279643]
 [0.24326789]]
b2: [[0.25232989]]
----------------------------------------
A2: [[1.87927919]]
****************************************


In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_11778/2166773343.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 *(y-y_hat)*A1[0][0])
/tmp/ipykernel_11778/2166773343.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 *(y-y_hat)*A1[1][0])
/tmp/ipykernel_11778/2166773343.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.

In [ ]:
parameters


{'W1': array([[0.20426455, 0.23610538],
        [0.20442189, 0.23646419]]),
 'b1': array([[0.01484644],
        [0.01487705]]),
 'W2': array([[0.27602518],
        [0.27859719]]),
 'b2': array([[0.28883863]])}

In [ ]:
##now inner loop is completed once means itrated to each student / sample once

In [ ]:
##epochs implementation
parameters = intialize_parameters([2,2,1])
epochs = 5
for i in range(epochs):
  Loss = []
  for j in range(df.shape[0]):
    x = df[['cgpa','profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]
    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append((y-y_hat)**2)
  print('Epoch -',i+1,'Loss -',np.array(Loss).mean())
parameters


A0: [[ 5]
 [12]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.7]
 [1.7]]
****************************************
A1: [[1.7]
 [1.7]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.34]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.10411545 0.10987708]
 [0.10411545 0.10987708]]
b1: [[0.00082309]
 [0.00082309]]
----------------------------------------
A1: [[1.77078575]
 [1.86873347]]
****************************************
A1: [[1.77078575]
 [1.86873347]]
W2: [[0.112444]
 [0.112444]]
b2: [[0.119764]]
----------------------------------------
A2: [[0.5290061]]
****************************************
A0: [[ 5]
 [12]]
W1: [[0.10985077 0.12364184]
 [0.10988993 0.12373582]]
b1: [[0.00197015]
 [0.00197799]]
----------------------------------------
A1: [[1.86990311]
 [2.10501708]]
****************************************
A1: [[1.86990311]
 [2.10501708]]
W2: [[0.12827834]
 [0.12915419]]
b2: [[0.1

{'W1': array([[0.22260571, 0.39425371],
        [0.24308788, 0.4434109 ]]),
 'b1': array([[0.02452114],
        [0.02861758]]),
 'W2': array([[0.37348396],
        [0.49714079]]),
 'b2': array([[0.5008071]])}

In [ ]:
###it gives detailed values of bias as well as for weights for each epoch


In [ ]:
## forward prop
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2 # num of layers in the neural network
  for l in range(1,L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    #print('W'+str(l)+':',W1)
    #print('b'+str(l)+':',b1)
    #print('--'*20)

    A = linear_forward(A_prev,W1,b1)
    #print('A'+str(l)+':',A)
    #print('**'*20)

  return A,A_prev


In [ ]:
##epochs implementation
parameters = intialize_parameters([2,2,1])
epochs = 5
for i in range(epochs):
  Loss = []
  for j in range(df.shape[0]):
    x = df[['cgpa','profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]
    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append((y-y_hat)**2)
  print('Epoch -',i+1,'Loss -',np.array(Loss).mean())
parameters


Epoch - 1 Loss - 25.020743966338067
Epoch - 2 Loss - 17.356620499488766
Epoch - 3 Loss - 8.062481735217396
Epoch - 4 Loss - 2.5860820103981954
Epoch - 5 Loss - 1.4782291248000072


{'W1': array([[0.22260571, 0.39425371],
        [0.24308788, 0.4434109 ]]),
 'b1': array([[0.02452114],
        [0.02861758]]),
 'W2': array([[0.37348396],
        [0.49714079]]),
 'b2': array([[0.5008071]])}

In [ ]:
#### its manual process now this process is done using keras library

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim = 2))
model.add(Dense(1,activation = 'linear'))

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
### keras assign random weights


In [ ]:
model.get_weights()

[array([[ 0.67139804, -0.6642387 ],
        [ 0.6348916 ,  0.29243708]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1719011],
        [1.3770968]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1,0.1],
 [0.1 ,0.1]],dtype = np.float32),
               np.array([0,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype = np.float32),
               np.array([0.],dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()


[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)
#here learning rate is set as 0.001


In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 27.8898 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.5776
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.2563
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.9013 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.5714
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.1944
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.8161
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.4491
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.0516
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.6600
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.2631
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23.8127
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23.3588
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.9282
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22.4823
Epoch 16/75
4/4 ━━

In [ ]:
model.get_weights()

[array([[0.37366712, 0.37366712],
        [0.36569276, 0.36569276]], dtype=float32),
 array([0.2724009, 0.2724009], dtype=float32),
 array([[0.37300605],
        [0.37300605]], dtype=float32),
 array([0.2048495], dtype=float32)]

In [ ]:
### classfication problem

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# creating a sample data
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placed'])

In [ ]:
## intialize w,b,layer dim
def intialize_parameters(layer_dims):

  np.random.seed(3)
  parameters ={}
  L = len(layer_dims)
  for l in range(1,L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
  return parameters

In [ ]:
##Utility function
def sigmoid(Z):
  A = 1/(1+np.exp(-Z))
  return A

In [ ]:
def linear_forward(A_prev,W,b):
  Z = np.dot(W.T,A_prev)+b
  A = sigmoid(Z)
  return A

In [ ]:
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2 # num of layers in the neural network
  for l in range(1,L+1):
    A_prev = A
    W1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    #print('A'+str(l-1)+':',A_prev)
    #print('W'+str(l)+':',W1)
    #print('b'+str(l)+':',b1)
    #print('--'*20)

    A = linear_forward(A_prev,W1,b1)
    #print('A'+str(l)+':',A)
    #print('**'*20)

  return A,A_prev

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 *(y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 *(y-y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 *(y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 *(y-y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 *(y-y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 *(y-y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 *(y-y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 *(y-y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 *(y-y_hat)*parameters['W2'][1][0])


In [ ]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['placed']].values[0][0]
# parameter intialization
parameters = intialize_parameters([2,2,1])

y_hat,A1= L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student-',-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

parameters

Loss for this student- 0.613402628898913


{'W1': array([[0.1003682, 0.1003682],
        [0.1003682, 0.1003682]]),
 'b1': array([[4.60243859e-05],
        [4.60243859e-05]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.10083997]])}

In [ ]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['placed']].values[1][0]
# parameter intialization
parameters = intialize_parameters([2,2,1])

y_hat,A1= L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student-',-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

parameters

Loss for this student- 0.613402628898913


{'W1': array([[0.10032217, 0.10041422],
        [0.10032217, 0.10041422]]),
 'b1': array([[4.60243859e-05],
        [4.60243859e-05]]),
 'W2': array([[0.10038148],
        [0.10038148]]),
 'b2': array([[0.10083997]])}

In [ ]:
X = df[['cgpa','profile_score']].values[2].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['placed']].values[2][0]
# parameter intialization
parameters = intialize_parameters([2,2,1])

y_hat,A1= L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student-',-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

parameters

Loss for this student- 0.7798063059256977


{'W1': array([[0.09967656, 0.09946093],
        [0.09967656, 0.09946093]]),
 'b1': array([[-5.3906548e-05],
        [-5.3906548e-05]]),
 'W2': array([[0.09954946],
        [0.09954946]]),
 'b2': array([[0.09900795]])}

In [ ]:
X = df[['cgpa','profile_score']].values[3].reshape(2,1) ## inputs
#shape (no of features , no of training example)
y = df[['placed']].values[3][0]
# parameter intialization
parameters = intialize_parameters([2,2,1])

y_hat,A1= L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student-',-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

parameters

Loss for this student- 0.768922894759937


{'W1': array([[0.09973281, 0.09973281],
        [0.09973281, 0.09973281]]),
 'b1': array([[-5.34383821e-05],
        [-5.34383821e-05]]),
 'W2': array([[0.0996078],
        [0.0996078]]),
 'b2': array([[0.09907131]])}

In [ ]:
##epochs implementation
parameters = intialize_parameters([2,2,1])
epochs = 5
for i in range(epochs):
  Loss = []
  for j in range(df.shape[0]):
    x = df[['cgpa','profile_score']].values[j].reshape(2,1)
    y = df[['placed']].values[j][0]
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]
    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
  print('Epoch -',i+1,'Loss -',np.array(Loss).mean())
parameters


Epoch - 1 Loss - 0.7121627519248996
Epoch - 2 Loss - 0.7009135539635659
Epoch - 3 Loss - 0.7008834601998722
Epoch - 4 Loss - 0.7008535079869148
Epoch - 5 Loss - 0.7008236965197454


{'W1': array([[0.09941227, 0.09941227],
        [0.09941227, 0.09941227]]),
 'b1': array([[-0.00011755],
        [-0.00011755]]),
 'W2': array([[0.09912133],
        [0.09912133]]),
 'b2': array([[0.09856054]])}

In [ ]:
new_weights = [np.array([[0.1,0.1],
 [0.1 ,0.1]],dtype = np.float32),
               np.array([0,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype = np.float32),
               np.array([0.],dtype=np.float32)]